### ISSUE TITLE
'ngx-alerts' is not a known element error in Angular 5

### ISSUE THREAD

**Issue by lijinlar** [MathijsBlok/ngx-alerts#1]
```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
'ngx-alerts' is not a known element:
```
Imported as follows,

`import { AlertService,AlertComponent } from 'ngx-alerts';`

**Comment by MathijsBlok** [comment]
Did you import the AlertModule.forRoot() in your app.module.ts? If you did, can you include an example of your code?

**Comment by lijinlar** [comment]
Yes, imported in app.module.ts but there had a conflict of BrowserModule, but I managed to fix it.

Then imported it in component like mentioned above.

( Sorry for not pasting the code , I have reverted and uninstalled plugin :( )

**Comment by MathijsBlok** [comment]
I'll start a new project and check if I can reproduce the error! :)

**Comment by MathijsBlok** [comment]
this seems to work

https://github.com/MathijsBlok/ngx-alerts-example

**Comment by lijinlar** [comment]
But BrowserModule can only be imported once in an app according to the error shown, That issue is still there.
I have figured out my actual problem.

My project structure is little bit complicated because of implementing tricky lazy load., and if I include your module in multiple modules it will cause 'BrowserModule is already loaded' error. I will check for some other work around to include ngx-alerts.

Thanks for info. :) 👍

**Comment by MathijsBlok** [comment]
Oh i'm sorry, i just now got it. It's because of the BrowserAnimationsModule in the AlertModule
I'll look into it!

**Comment by MathijsBlok** [comment]
I built a new version (1.1.0) that doesn't include the BrowsernimationModule, so you have to import it yourself in your CoreModule, or AppModule, i think that should fix it!

**Comment by lijinlar** [comment]
Have you missed something in build,

Now module is not available.

`error TS2307: Cannot find module 'ngx-alerts'`

![capture](https://user-images.githubusercontent.com/16028009/33940432-f380c6d0-e034-11e7-825b-14a9bed0a0e2.PNG)

**Comment by MathijsBlok** [comment]
Sorry published the src directory instead of the dist directory, it should work now with version 1.2.0

**Comment by lijinlar** [comment]
Kudooos...! It worked. Thanks. 💯

**Comment by MathijsBlok** [comment]
Haha awesome! Happy to help! :)
